const fs = require('fs-extra');
const path = require('path');
const http = require('http');
const { logInfo, logSuccess } = require('./logger');
const { installDevDependency } = require('./packageManager');

const SONAR_PROPS_FILE = 'sonar-project.properties';

// ---------------------------------------------------------------
// SonarQube server configuration
// Currently pointing to local Docker instance for testing
// Switch to GCP later by changing SONAR_HOST_URL and SONAR_TOKEN
// ---------------------------------------------------------------
const SONAR_HOST_URL = 'http://192.168.1.72:9000';
const SONAR_TOKEN    = 'sqa_4579719d9a294abff391f803ddb08ca6d32d27c5';
// const SONAR_ORG   = 'arjunlatiwala'; // only needed for SonarCloud

// Auto-create project on SonarQube via API so developer never needs to do it manually
async function ensureProjectExists(projectKey, projectName) {
  return new Promise((resolve) => {
    const auth = Buffer.from(`${SONAR_TOKEN}:`).toString('base64');
    const postData = `name=${encodeURIComponent(projectName)}&project=${encodeURIComponent(projectKey)}`;

    const options = {
      hostname: '192.168.1.72',
      port: 9000,
      path: '/api/projects/create',
      method: 'POST',
      headers: {
        'Authorization': `Basic ${auth}`,
        'Content-Type': 'application/x-www-form-urlencoded',
        'Content-Length': Buffer.byteLength(postData)
      }
    };

    const req = http.request(options, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        if (res.statusCode === 200 || res.statusCode === 201) {
          logSuccess(`SonarQube project "${projectKey}" created automatically.`);
        } else if (res.statusCode === 400 && data.includes('already exists')) {
          logInfo(`SonarQube project "${projectKey}" already exists.`);
        } else {
          logInfo(`SonarQube project setup: ${res.statusCode} — continuing anyway.`);
        }
        resolve();
      });
    });

    req.on('error', (err) => {
      logInfo(`SonarQube server unreachable — skipping project creation. (${err.message})`);
      resolve();
    });

    req.write(postData);
    req.end();
  });
}

exports.installSonarScanner = async () => {
  logInfo('Installing sonarqube-scanner as a dev dependency...');
  await installDevDependency('sonarqube-scanner');
  logSuccess('sonarqube-scanner installed.');
};

exports.setupSonarProperties = async () => {
  const propsPath = path.join(process.cwd(), SONAR_PROPS_FILE);

  const pkgPath = path.join(process.cwd(), 'package.json');
  let projectKey  = 'my-project';
  let projectName = 'My Project';

  if (await fs.pathExists(pkgPath)) {
    const pkg = await fs.readJSON(pkgPath);
    if (pkg.name) {
      projectKey  = pkg.name.replace(/[^a-zA-Z0-9_\-.:]/g, '_');
      projectName = pkg.name;
    }
  }

  // Auto-create project so developer never needs to do it manually
  logInfo(`Setting up SonarQube project "${projectKey}"...`);
  await ensureProjectExists(projectKey, projectName);

  const content = `# ---------------------------------------------------------------
# SonarQube configuration — auto-generated by secure-husky-setup
# Do not edit manually
# ---------------------------------------------------------------
sonar.host.url=${SONAR_HOST_URL}
sonar.login=${SONAR_TOKEN}
sonar.projectKey=${projectKey}
sonar.projectName=${projectName}
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**,.husky/**,.tools/**
`;

  await fs.writeFile(propsPath, content);
  logSuccess(`${SONAR_PROPS_FILE} configured automatically.`);
};