const fs = require('fs-extra');
const path = require('path');
const { logInfo, logSuccess, logError } = require('./logger');
const { installDevDependency } = require('./packageManager');

const SONAR_PROPS_FILE = 'sonar-project.properties';

exports.installSonarScanner = async () => {
  logInfo('Installing sonarqube-scanner as a dev dependency...');
  await installDevDependency('sonarqube-scanner');
  logSuccess('sonarqube-scanner installed.');
};

exports.setupSonarProperties = async () => {
  const propsPath = path.join(process.cwd(), SONAR_PROPS_FILE);

  if (await fs.pathExists(propsPath)) {
    logInfo(`${SONAR_PROPS_FILE} already exists. Skipping creation.`);
    return;
  }

  const pkgPath = path.join(process.cwd(), 'package.json');
  let projectKey = 'my-project';
  let projectName = 'My Project';

  if (await fs.pathExists(pkgPath)) {
    const pkg = await fs.readJSON(pkgPath);
    if (pkg.name) {
      projectKey = pkg.name.replace(/[^a-zA-Z0-9_\-.:]/g, '_');
      projectName = pkg.name;
    }
  }

  // Fixed by Arjun — added sonar.organization (required by SonarCloud)
  // and sonar.host.url uncommented pointing to SonarCloud by default.
  // SonarQube step in pre-commit hook will skip gracefully if not configured.
  const content = `# ---------------------------------------------------------------
# SonarQube / SonarCloud project configuration
# Generated by secure-husky-setup
# ---------------------------------------------------------------

# --- Required: update these before using SonarQube ---
sonar.host.url=https://sonarcloud.io
sonar.organization=YOUR_ORGANIZATION_KEY
sonar.token=YOUR_TOKEN_HERE

# --- Project info (auto-filled from package.json) ---
sonar.projectKey=${projectKey}
sonar.projectName=${projectName}
sonar.projectVersion=1.0

# --- Source settings ---
sonar.sources=.
sonar.sourceEncoding=UTF-8

# --- Exclusions ---
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**,.husky/**,.tools/**
`;

  await fs.writeFile(propsPath, content);
  logSuccess(`${SONAR_PROPS_FILE} created.`);
  logInfo(`Next steps for SonarQube:`);
  logInfo(`  1. Set sonar.organization  → your SonarCloud org key`);
  logInfo(`  2. Set sonar.token         → your SonarCloud token`);
  logInfo(`  Until configured, SonarQube step will be skipped automatically.`);
};